name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v3
        with:
          version: 5.4

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build

      - uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: build
          single-commit: true
